frontend:
  image: ninesun0318/frontend
  tag: '24250d2'
  autoscaling:
    averageUtilization: 90
backend:
  image: ninesun0318/backend
  tag: '24250d2'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  