frontend:
  image: ninesun0318/frontend
  tag: 'bae6f72'
  autoscaling:
    averageUtilization: 90
backend:
  image: ninesun0318/backend
  tag: 'bae6f72'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  