frontend:
  image: ninesun0318/frontend
  tag: 'bbb719f'
  autoscaling:
    averageUtilization: 90
backend:
  image: ninesun0318/backend
  tag: 'bbb719f'
  autoscaling:
    averageUtilization: 90
database:
  enabled: true
  uri: pg-service
  username: postgres
  password: postgres
  